name: CheckAction
on: 
  push:
    branches:
    - 'v[0-9]+.[0-9]+'

jobs:
  scanRepo:
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest

    #Check
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ''
        ref: ''

    #Scan
    - name: Scan repo
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        output: 'trivyReport.txt'
        ignore-unfixed: true
        exit-code: '1'
        severity: 'CRITICAL'

    #SuccessBranch
    #Build and push Dockerhub
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/cicd-workshop:${{github.sha}}
    
    #Sign
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
      with:
        cosign-release: 'v2.1.1'

    - name: Sign image with a key
      run: cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${{secrets.DOCKERHUB_USERNAME}}/cicd-workshop:@${DIGEST}"
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}

    - name: Verify
      run: cosign verify --key cosign.pub "${{secrets.DOCKERHUB_USERNAME}}/cicd-workshop:@${{ steps.build-and-push.outputs.digest }}" | jq .

    #Send notification
    - name: Slack successful notification
      id: send
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: "Image build and signed"
        SLACK_MESSAGE: "Name: Cheng Siyuan\nMetriculation: A0287262X\nEmail: e1285208@u.nus.edu\nGit: https://github.com/${{github.repository}}\nImage: https://hub.docker.com/repository/docker/evacdot/cicd-workshop"

    #FailBranch
    #Send notification
    - name: Slack Fail Notification
      if: ${{failure()}}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: "Scan Failed"
        SLACK_MESSAGE: "Failed trivy scan, see uploaded report."

    #Report file
    - name: Upload report
      if: ${{failure()}}
      uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ secrets.SLACK_BOT_TOKEN}}
        channel_id: ${{secrets.CHANNEL_ID}}
        file_path: './trivyReport.txt'
        initial_comment: 'Post by Cheng Siyuan'